[workspace]
members = [
	"ch01-recursive/t1-luffy-eats-peach",
	"ch01-recursive/t2-diving-board",
	"ch01-recursive/t3-exponential-enumeration",
	"ch01-recursive/t4-combination-enumeration",
	"ch01-recursive/t5-permutation-enumeration",
	"ch02-struct/s1-order-list",
	"ch02-struct/s2-one-direction-cycle-list",
	"ch02-struct/s3-biodirection-list",
	"ch02-struct/s4-happy-number",
	"ch02-struct/s5-rotate-right",
	"ch02-struct/s6-del-node",
	"ch02-struct/s7-detect-cycle",
	"ch02-struct/s8-reverse-v2",
	"ch03-stack/s1-leetcode-20",
	"",
	"",
	"",
	"",
]
