[package]
name = "s1-leetcode-20"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ds_lib = { git = "https://github.com/linonon/ds_lib.git"}