[package]
name = "s5-rotate-right"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ds_lib = { path = "D:\\Workspace\\ds_lib"}